{% set name = "h11" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f19fbbe99e72420ff35c00b27a34cb9937e902a8b810e2c88300c6f0a3b699d

build:
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - typing_extensions  # [py<38]
    - wheel
  run:
    - python

test:
  imports:
    - h11
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-hyper/h11
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A pure-Python HTTP/1.1 protocol library.'
  description: |
    h11 is an HTTP/1.1 protocol library written in Python, heavily inspired by
    [hyper-h2](https://hyper-h2.readthedocs.io/en/stable/).
  doc_url: https://h11.readthedocs.io/
  dev_url: https://github.com/python-hyper/h11

extra:
  recipe-maintainers:
    - carlodri
