travis:
  secure:
    BINSTAR_TOKEN: Ls9CNyivAVyd8WITRa8M4PyjJ3nnvCX7oBWBk0yWgH2P4vtYVyRixX6FsMeZ6arHBelGZ+IDu0MCLkGazpjNRgp/tH1YdSRxxO0PIFxZwNafbdT28H7zVdjIdQuYV7kModo1JXIjsgiPwZhcZR3pjdh2aIOeVcMQk/0KD1XfmuYR80DEf1Eyo94tpMXZMGhUJlsKCLABS36YtNM81hbcsLJd40xTqLzMP5GeDaR09qKqXlQImCmC0c6J+BNNeCWjUDBbymQpkuh8PBfEQO1UJgfTaRz93Xm6OBE1O4bB8H/VNOnSmgOrdnz0HblvYER5Biw63wXak3dbHQ+u1K9+FobbRb/Ubq9OFYHj3atveUuYlkkvUeVqWFy0Bd9VERVDe4aQLpmsCOjD2l4/jYWXsMFxzTObxwRaBa/K+K7Z2jolUAGo7d8m407tAoCjHFTdR50GlAWTIWxz8aI3HnmzRSkvT/SAR3oo2FiK+4E9l3sxv5u1BAjs/vtgNNLg4bspGbl0EhR3XZCFXeGWZQWILnkjhC2HzpXt2zF4mh069geBrHr0dmsY1tZgNLThnvX6ATce9B0x8KeRSE4DEHIszg4w+2zKANj7s/7OKuQC/I7Jw9FOH0wDJdKN+pIkUYbsbfIAHnIWk4cnCdaV0CGGWneG4a/Lf6rESZy2PmhUwMM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
